Repository DivideE-ConqueR/confessions-server, pull requests merged in 2022-09, with the labels that each got.

#2 Connect to MongoDB
  .gitignore
  package.json
  src/routes/test.js
  src/server.js
  yarn.lock
Labels: enhancement, good first issue

#5 Push to dev
  package.json
  src/models/Post.js
  src/routes/posts.js
  src/routes/test.js
  src/server.js
  yarn.lock
Labels: enhancement, dev

#6 Complete posts route
  src/models/Post.js
Labels: enhancement, dev

#7 Likes dislikes
  src/routes/dislikes.js
  src/routes/likes.js
  src/server.js
Labels: enhancement, good first issue

#8 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement, good first issue, dependencies
