Repository DivideE-ConqueR/confessions-server, pull requests merged in 2023-02, with the labels that each got.

#47 Prettier branch update
  package.json
  yarn.lock
Labels: good first issue, dependencies

#50 Search
  src/routes/search.js
  src/server.js
Labels: enhancement, good first issue, dev

#56 Middleware
  package.json
  src/middleware/cache.js
  src/middleware/rate-limit.js
  src/routes/comments.js
  src/routes/posts.js
  src/routes/search.js
  src/routes/sync.js
  src/server.js
  yarn.lock
Labels: enhancement, dev
